---
title: "Description of data/processed/characters.csv"
author: "Jill"
date: "1/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# characters.csv

The characters.csv file lists all Characters that interact with machine vision technologies in the Creative Works. Data includes race/ethnicity, gender, species, age, and sexuality. as (see Table 5). More information on the process of assigning race, gender and sexuality to the Characters is given in the Ethics Statement below.

90 of the characters are “group” characters, such as the Gamemasters in The Hunger Games. Here we have assigned values to the fields they have in common (Age: Adult, Species: Human, RaceOrEthnicity: White). The Gamemasters include both men and women. Rather than allow multiple values for a trait we have opted to leave the trait as “Unknown” in cases like this. The Gamemasters’ sexual preferances aren’t all made explicit, so Sexuality is also marked as “Unknown”. Unknown is thus a term that can include cases where a trait is not made explicit in the work as well as cases where the trait is not applicable to the character or group of characters.

There is one row for each character, except in four cases: CharacterID 2734 has been assigned two species: animal and machine. Three characters are transgender women, and we have given them two values in the Gender field: “Trans” and “Female”. The 500 works we analysed have no transgender men interacting with machine vision technologies.


### Fields in characters.csv.

| Column header    | Description                                                                                                                                                                                                                                                                                                                                      |
|------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| CharacterID	     | A number that uniquely identifies this item in the dataset. 	                                                                                                                                                                                                                                                                                    |
| Character	       | The name or title of a Character. If the name can be mistaken for another one in the dataset, it is followed by the title of the Creative Work in which the character appears, in parentheses. Quotation marks are used to indicate personas, or representations of real people. For an explanation of personas see the Ethics Statement below.	 |
| Species	         | Animal, Cyborg, Fictional Species, Human, Machine, Unknown.	                                                                                                                                                                                                                                                                                     |
| Gender	          | Female, Male, Non-binary/Other, Trans, Unknown.	                                                                                                                                                                                                                                                                                                 |
| RaceOrEthnicity	 | Asian, Black, White, Person of colour, Immigrant, Indigenous, Complex, Unknown.                                                                                                                                                                                                                                                                  |
| Age	             | Child, Young adult, Adult, Elderly, Unknown.	                                                                                                                                                                                                                                                                                                    |
| Sexuality	       | Homosexual, Heterosexual, Bi-sexual, Other, Unknown.	                                                                                                                                                                                                                                                                                            |
| IsGroup	         | A Boolean true/false variable, where TRUE means that the entry describes a groups of several people acting together.                                                                                                                                                                                                                             |
| IsCustomizable   | A Boolean true/false variable, where TRUE means that the character can be customized by the user. All customizable characters in the dataset are player-characters in video games.                                                                                                                                                               |
